### ISSUE TITLE
Need a way to configure electron prior to app 'ready'

### ISSUE THREAD

**Issue by dannysu** [jprichardson/electron-mocha#106]
There are certain things that can only be configured before the 'ready' event is fired. E.g. [disableHardwareAcceleration()](https://electron.atom.io/docs/api/app/#appdisablehardwareacceleration)

Currently the `--require-main` is only executed after the 'ready' event.

I can make a patch to enable the ability to run code prior to the 'ready' event, but wanted to get advice on the preferred design.

If not worrying about backwards compatibility, then moving the `--required-main` logic outside of `app.on('ready'` can work. If anyone needs to run logic only after the 'ready' event, their `--require-main` file can use `app.prependListener('ready'` to ensure that it's run first. And for anyone that needs to configure electron prior to the 'ready' event, they can use the same file without waiting for any events.

For example:
```
// --required-main file
const {app} = require('electron');

console.log("code here runs prior to 'ready' event");

app.prependListener('ready', function() {
    console.log("code here runs after 'ready' event but before tests");
});
```

However, since it's an existing feature, change of behavior is undesirable. I'm wondering what would be the preferred name for the file that runs prior to 'ready'? `--require-before-ready`?

Thanks

**Comment by inukshuk** [comment]
Good point. Both suggestions sound OK to me(loading `--require-main` before app ready and bumping major or to add a new `--require-before-main`) -- my preference would be to move `--require-main` out of app ready. @jprichardson what do you think?

**Comment by jprichardson** [comment]
> my preference would be to move --require-main out of app ready. @jprichardson what do you think?

Yep, sounds good. Do you think it should be a major change since it may introduce regressions? I'm thinking so to be safe.

**Comment by inukshuk** [comment]
Yes, let's bump the major version to be on the safe side.

**Comment by dannysu** [comment]
Thanks!
