### ISSUE TITLE
--require-main does not use --compilers flag

### ISSUE THREAD

**Issue by pronebird** [jprichardson/electron-mocha#108]
```electron-mocha --renderer -R spec --compilers js:babel-core/register --require-main test/setup/main.js test/*.spec.js```

Throws `Unexpected token import`.

Is there any way to enable babel compiler for main JS?

**Comment by inukshuk** [comment]
The reason for `--require-main` is to run as early as possible (to allow modifications before Electron's `ready` event), that's why it is loaded before all other mocha options. I'm inclined to leave it this way, but what is the reason for using `--require-main` instead of `--require` in your case?

**Comment by pronebird** [comment]
Honestly I can't tell what `--require` does from description:

```
-r, --require <name>   require the given module
```

All I need to do is to run some code in main process before tests start.

**Comment by inukshuk** [comment]
It's the same as in 'regular' mocha: it runs your code before the tests start in the process in which mocha runs. So by default, you'd use `--require` as you would in mocha.

`--require-main` is for special situations where you need to run something in main either before the ready event, or if you're testing in `--renderer` but still need to run some code in main.

**Comment by pronebird** [comment]
Indeed, so that's my case where I have to initialize some library in main process, while running tests in renderer. That's why I asked about babel and `--require-main`.

**Comment by inukshuk** [comment]
In that case, just require `babel-core/register` before your own setup code.

**Comment by pronebird** [comment]
OK got it. Thanks.

**Comment by pronebird** [comment]
@inukshuk revisiting this problem once again after migrating to TypeScript. Basically here is what I do:

```
electron-mocha --renderer --reporter spec --require ts-node/register --require-main ts-node/register --require-main "test/setup/main.ts" --preload "test/setup/renderer.ts" "test/*.spec.ts"
```

And what happens is, the `--preload` script is not executed at all. I assume that `electron-mocha` expects a plain Javascript, is this correct?

**Comment by inukshuk** [comment]
The preload scripts are inserted in the renderer's browser window using script tags before mocha runs; it's intended mostly for people testing UMD modules or websites, not really for Electron apps. I don't know what `ts-node/register` does, but if it hooks into `require` for instance, it would certainly not convert your preload scripts.
