### ISSUE TITLE
Cannot run in cygwin on Windows?

### ISSUE THREAD

**Issue by AllisonLamm** [jprichardson/electron-mocha#11]
I can run just fine in Windows cmd with electron defined and point to the index.js file  ( you'll see error messages because I haven't passed the proper test directory, but it does work): 

`electron "C:\Users\alamm\AppData\Roaming\npm\node_modules\electron-mocha\index.js"`
`[4352:0902/094154:INFO:CONSOLE(0)] made it to index.js`
`[4352:0902/094154:INFO:CONSOLE(0)] [Error: cannot resolve path (or pattern) 'test']`

While in cygwin I get absolutely no output...

`electron "C:\Users\alamm\AppData\Roaming\npm\node_modules\electron-mocha\index.js" `
`---- missing output here.... ------`

**Comment by jprichardson** [comment]
Honestly, not sure. I haven't used cygwin in a long time. I'll leave this open with the hopes of someone else coming along with a solution.

**Comment by jprichardson** [comment]
I suspect if you modify this file: https://github.com/jprichardson/electron-mocha/blob/0.4.0/bin/electron-mocha to use npm:`win-spawn` instead of node:`spawn` it may work. If it does, pull request welcome.

**Comment by AllisonLamm** [comment]
Thank for the reply! I tried the fix and it wasn't an immediate game changer. I have plans to spend more time figuring out the root cause of this issue, but I can't provide an exact time frame. I'll keep this issue up to date as I find time to continue researching the issue.

**Comment by jprichardson** [comment]
Please try https://www.npmjs.com/package/cross-spawn. Apparently it's much better than `win-spawn`.

**Comment by jprichardson** [comment]
If it works, I'll accept it into `electron-mocha`.

**Comment by inukshuk** [comment]
@AllisonLamm the environment variable [ELECTRON_NO_ATTACH_CONSOLE](http://electron.atom.io/docs/api/environment-variables/#electronnoattachconsole-windows) may help solve this -- I don't regularly use Windows, so it's just a wild guess, but this helped me get output on AppVeyor. If cygwin gets the console output via RDP (as AppVeyor does) then this will likely help.

**Comment by AllisonLamm** [comment]
The issue is resolved in the current build! Not sure exactly what has resolved the issue, but this is safe to close now.
