### ISSUE TITLE
npm test fails when run with jenkins

### ISSUE THREAD

**Issue by TalKashi** [jprichardson/electron-mocha#114]
Hi,
I am having issue running electron-mocha with jenkins.
I have a windows 10 machine which running Cygwin. Jenkins is connecting via ssh to the machine and perform the 'npm test' call (with prior call to 'npm install'). I have a dummy test which assert true to be true, the test is passing but for some reason electron-mocha exit code is 255, which is failing my pipeline. If I run the test on my developer machine it is working or if I am connecting via RDP to the jenkins machine it is also working.

I have tried to debug it in several ways, and even if I run 'electron-mocha --version' it still fails.
I have also debugged the electron-mocha script and I noticed it spawns the electron process and return it's status as this process.exit(status):
``` javascript
child.on('exit', function (code) {  process.exit(code) }) 
```
If I change it to always exit on 0 it works:
``` javascript
child.on('exit', function (code) {  process.exit(0) }) 
```
I have also tried to install the xvfb plugin but still same error.
This is the final output from jenikns (without modifying the electron-mocha script):
```
> xvfb-maybe electron-mocha ./tests/dummyTest.js --timeout 100000
[0m[0m
[0m  Dummy test[0m
  [32m  âˆš[0m[90m should always pass[0m


[92m [0m[32m 1 passing[0m[90m (14ms)[0m

Failed with exit code: 255
Output:

npm ERR! Test failed.  See above for more details.
Build step 'Execute shell' marked build as failure
```

Using electron 1.7.6 and latest electron-mocha

If you need more info of the script/environment just ask.
Any help or guidance is appreciated! Thanks ahead!

**Comment by inukshuk** [comment]
Would be good to know which version of Electron you're using?

**Comment by TalKashi** [comment]
you are right :) edited my post.
Electron 1.7.6 and latest electron-mocha

**Comment by inukshuk** [comment]
I can't reproduce this, but have you tried what the exit code of running Electron in your environment is?

Otherwise, I would suggest to debug our add `console.log` statements at electron-mocha's [index.jsh](ttps://github.com/jprichardson/electron-mocha/blob/master/index.js) to see what exit path is taken and what exit code supplied (normally it should be the number of failed tests) to check if electron-mocha returns 255 or if electron does.
