### ISSUE TITLE
Running on a headless Mac Mini server

### ISSUE THREAD

**Issue by jviotti** [jprichardson/electron-mocha#118]
I get the following error when running on a headless Mac Mini server over SSH:

```sh
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
```

Do you have any pointers on what the fix could be? Its weird that `electron-mocha` runs fine on Travis CI macOS builds though.

**Comment by adeperio** [comment]
Getting this issue too

**Comment by nickensoul** [comment]
@jviotti did you solved this? faced this with ssh + mac mini server + electron 3.1.3 running development server.

**Comment by jviotti** [comment]
@nickensoul Not really. We ended up making sure we graphically login to our Mac workers before attempting to run any job.

**Comment by nickensoul** [comment]
@jviotti using `sudo` make it works.
Too weird, but we will use this temporary solution. For anybody solved this or got this issue too, please let us know!

**Comment by gtritchie** [comment]
Also hitting this, getting:

2022-03-23 10:06:02.727 Electron[85647:620799] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted

Then it just hangs until I Ctrl+C it.

Wanting to run unit tests on our rented Mac builder machine where we only have ssh (non-root) access. Doesn't seem like it's possible?

Might have to be content with only running these tests on our Linux docker containers.

**Comment by jviotti** [comment]
Closing stale issues
