### ISSUE TITLE
README clairifcation: jsdom as prerequisite for testing renderer?

### ISSUE THREAD

**Issue by quadrophobiac** [jprichardson/electron-mocha#12]
Hello there,

I've started using your test suite as its really useful.

However I'm at a loss as to how to extend the renderer test example that you have included in the repository but by chance discovered that the syntax seems exactly the same as jsdom. I'm aware that what I'm asking might be novice level oblivious but  
Basically I can use jsdom (below) to create an empty window.document object, which can then be populated with divs or whatever elements you need to mock for your DOM testing. 

The phrasing on your repo makes it seem like this repository is all that is needed for testing elements in the DOM, so is jsdom part of the electron-mocha package?

    jsdom()
    
    it('has document', function () {
      var div = document.createElement('div')
      expect(div.nodeName).eql('DIV')
    })

**Comment by jprichardson** [comment]
Create a file named `test.js`. In it, put the following:

```js
var assert = require('assert')

it('something', function () {
  var div = document.createElement('div')
  assert.strictEqual(div.nodeName, 'DIV')
})
```

Run like:

    electron-mocha --renderer test.js

The expected result:

      ✓ something

     1 passing (32ms)

Does that help?

**Comment by quadrophobiac** [comment]
Hey there,

Thanks for the clarification! That syntax closely resembles jsdom https://www.npmjs.com/package/mocha-jsdom - is that the package being utilised?

cheers!

**Comment by jprichardson** [comment]
No, `jsdom` is an emulation of the DOM in Node.js. If using it, you'll miss out on most non-DOM APIs (any web API that isn't DOM related e.g. websockets, web storage, etc). `electron-mocha` is a real DOM using Chrome and thus, you get every web API available in Chrome.
