### ISSUE TITLE
Cannot launched when electron-prebuilt-compile is available

### ISSUE THREAD

**Issue by phbernard** [jprichardson/electron-mocha#125]
Since https://github.com/jprichardson/electron-mocha/pull/111, `electron-prebuilt-compile` is tested to determine what the `electron` variable should be.

However, when it is available, `resolve('electron-prebuilt-compile')` returns an empty hash, thus it is selected when previous proposals fail. Because this is not a valid path, `electron-mocha` fails with:

    child_process.js:380
        throw new TypeError('"file" argument must be a non-empty string');
        ^

    TypeError: "file" argument must be a non-empty string
        at normalizeSpawnArguments (child_process.js:380:11)
        at exports.spawn (child_process.js:493:38)
        (...)

Simply dropping this statement make electron-mocha work again. However, the poinf of https://github.com/jprichardson/electron-mocha/issues/110 and https://github.com/jprichardson/electron-mocha/pull/111 is to make electron-mocha compatible with electron-forge, which is my case. So I'm not sure of how to handle this.

Was it wrong to test `electron-prebuilt-compile`? Do I miss something?

**Comment by phbernard** [comment]
Well actually there is no executable for `electron-prebuilt-compile`. I don't know how this module could end up in the search path (again, a change from https://github.com/jprichardson/electron-mocha/pull/111).

My advice is to simply remove the line (so undo half of https://github.com/jprichardson/electron-mocha/pull/111). But as I don't understand why the module was here in the first place, I'm not confident with that fix.

**Comment by phbernard** [comment]
I wanted to ping the guy how submitted https://github.com/jprichardson/electron-mocha/pull/111. Unfortunately his account was deleted :(

**Comment by inukshuk** [comment]
OK I removed the electron-compile from the list of NPM resolution completely; I guess #111 was misguided.

In any case, I hope it works for you again. Please note that you can also set `ELECTRON_PATH` as an environmet variable (pointing it to the `electron` binary you want to use) if the automatic resolution does not work.

**Comment by phbernard** [comment]
It now works with latest 6.0.2 release. Thanks!
