### ISSUE TITLE
Is there a way to specify options per-test or per-suite?

### ISSUE THREAD

**Issue by jwir3** [jprichardson/electron-mocha#126]
We are running `electron-mocha` in the following way:
```
electron-mocha tests/integration --opts ./tests/integration/mocha.opts
```

With the following options:
```
--recursive
--ignore-gpu-blacklist
--enable-logging
--renderer
--timeout=130000
```

With a test similar to the following:

```
context ('Shadows', () => {
  // Shadow tests are slow...
  // this.slow(500); // throws an error

  context('a box with a fill', () => {
    it ('does something that takes a while', async () => {
      ...
    });
  });
});
```

As I mention in the code above, `this.slow(500);` throws an error:
```
this.slow is not a function
TypeError: this.slow is not a function
```

Is there a way to do this that will allow me to specify the 'slow' ms without having to do it globally? (I'd like to specify it only for these shadow tests).

**Comment by inukshuk** [comment]
You're using arrow functions, so `this` will be bound to the `this` of the defining context. If you want to access the context bound to describe/it by mocha you can't use arrow functions.
