### ISSUE TITLE
--require option not apply to renderer process

### ISSUE THREAD

**Issue by jhen0409** [jprichardson/electron-mocha#13]
Hey,
I use `babel` writing code. I use following command run `main` process tests:

```
electron-mocha -r 'babel/register' ./tests
```

But it will not work in `renderer` process (--renderer), I must edit the `renderer/index.js`:

```
require('babel/register')
require('./run')
```

**Comment by jprichardson** [comment]
Does the compiler option work for you for this?

**Comment by jhen0409** [comment]
@jprichardson yeah, I can use the `compilers` option in the new version! Thanks @vidbina!

**Comment by inukshuk** [comment]
Would you mind if I adjusted this? I'm not talking about babel here, but requires for example to include custom matchers, test helpers etc. -- that's what the option is used normally, isn't it? All that becomes pretty pointless if it doesn't run in the renderer.
