### ISSUE TITLE
Natively compiled module sqlite3 crash

### ISSUE THREAD

**Issue by ChrisHSandN** [jprichardson/electron-mocha#130]
### To Replicate
Create a project with Electron 2 and [node-sqlite3](https://github.com/mapbox/node-sqlite3) and run a electron-mocha --renderer test which contains a `require('sqlite3')`

### Error
```
Method bytesRead called on incompatible receiver #<Pipe>
TypeError: Method bytesRead called on incompatible receiver #<Pipe>
...
```

### Fix
Removing these lines from console.js fixes the issue:
```
Object.defineProperty(process, 'stdout', {
  value: remote.process.stdout
})
```
Everything seems to continue to work fine, so I’m not if these lines are even needed anymore.

Someone has also reported the same issue on the electron issue tracker here: https://github.com/electron/electron/issues/13061

**Comment by inukshuk** [comment]
Yes, it's not possible to pipe over remote. I think you're right and we don't need to forward stdout anymore.
