### ISSUE TITLE
Generating performance reports?

### ISSUE THREAD

**Issue by Glinkis** [jprichardson/electron-mocha#132]
When I enable the `--interactive` flag, it opens an electron window in which I can see the test in the console.

Now, would it be possible to inspect the performance of the tests in that window?
I cannot run the tests after having pressed the record button, as I am then unable to refresh the window to rerun the tests.

<img width="182" alt="screen shot 2018-06-29 at 15 54 40" src="https://user-images.githubusercontent.com/8037927/42096131-c988223a-7bb4-11e8-82e1-7d0648cf2575.png">

**Comment by inukshuk** [comment]
Can you start recording while paused in the debugger? If so you could start interactive and add a `debugger` statement before your tests start (or set a breakpoint in the sources tab and reload). Does that work?
