### ISSUE TITLE
Race condition that causes crash in Electron 3.0

### ISSUE THREAD

**Issue by pronebird** [jprichardson/electron-mocha#133]
Hi,

Just stumbled upon this error in our tests (electron-mocha@6.0.4):
<img width="488" alt="screenshot 2018-10-09 at 14 14 40" src="https://user-images.githubusercontent.com/704044/46668789-cfcf3e80-cbcd-11e8-97b7-a453230398a3.png">

Couldn't reproduce, seems like some sort of race condition. May be worth looking into which resources allocated by electron-mocha do not live long enough.

**Comment by inukshuk** [comment]
FWIW I've had no issues with 3.0 so far.
