### ISSUE TITLE
Incompatible with Node v8 and Electron < 3

### ISSUE THREAD

**Issue by pronebird** [jprichardson/electron-mocha#139]
We support older Electrons in our library, so the following tests stopped working after updating to the latest electron-mocha.

>$ node --version
>v8.9.3
>App threw an error during load
>TypeError: app.whenReady is not a function

>$ node --version
>v8.15.1
>App threw an error during load
>~/node_modules/electron-mocha/lib/run.js:164
>          { ...argv, files },

**Comment by pronebird** [comment]
Makes sense. I agree, we should not bother about Electron 1.x versions anymore since it's way too old.

**Comment by inukshuk** [comment]
I got rid of the `whenReady()` call and this seems to make at least [our own tests pass](https://travis-ci.org/jprichardson/electron-mocha).
