### ISSUE TITLE
Add option to show browser window and report there?

### ISSUE THREAD

**Issue by kress95** [jprichardson/electron-mocha#14]

**Comment by jprichardson** [comment]
Why would you want to do this?

**Comment by kress95** [comment]
Easier canvas debugging.
And loca reporter output is pretty nice on devtools.

**Comment by rgbkrk** [comment]
I'd prefer to keep the console based output. This also seems like a lot of work just to get out a way to debug something visually. Would be kind of neat to watch my test suites run through though. :wink:

**Comment by kress95** [comment]
Since electron-mocha is console focused, maybe it's better to write a separate tool just for that :laughing:
