### ISSUE TITLE
Unexpected characters in test results "ΓêÜ" on Windows

### ISSUE THREAD

**Issue by jordanapplewhite** [jprichardson/electron-mocha#140]
Hi, I'm on Windows 10 and getting some weird characters in the test results in the console. This happens when using the terminal in VSCode and when using powershell. Characters are ΓêÜ, looks like this:

![image](https://user-images.githubusercontent.com/5913/56385630-bb5ba680-61ed-11e9-98cf-b1c1cf99b805.png)

I imagine that's just a checkmark being decoded incorrectly by the windows terminal. It's not a big deal, just wondering if you know a fix. Thanks!

**Comment by inukshuk** [comment]
Does `chcp 65001` help?

**Comment by jordanapplewhite** [comment]
It sure does. I had never heard of chcp 65001. Thanks!

**Comment by Mr1008** [comment]
Why does chcp 65001 is needed since for simply running mocha itself it's not? Also for some reason colors are away since in mocha they work. Strange. 

Also it seems that running tests with electron-mocha makes them stop running on first failing test with only an exception message (with no trace) like ```× ERROR: Invalid or unexpected token``` while running mocha with same arguments works as expected. All tests are executed with proper stacktraces logged at the end (and X next to test name)

**Comment by inukshuk** [comment]
I think mocha will try to detect your terminal's capabilities, like color, and the auto-detection yields different results in Node.js and Electron (especially in renderer, which will likely get detected as a browser). Do colors works when you pass `-c` specifically?

As for missing stack traces, it depends on your exact configuration (most importantly if your tests run in main or `--renderer`). If you can point me to an example I can take a look.

**Comment by Mr1008** [comment]
Yeah, it is possible although for some reason everything was ok in older version of electron-mocha. Unfortunately it does not seem to work with node 12.

This is how it looks like without chcp command:
![image](https://user-images.githubusercontent.com/1630067/56913738-b979c900-6ab2-11e9-8aa6-a2cbe2bfe890.png)

This is after chcp:
![image](https://user-images.githubusercontent.com/1630067/56913778-cac2d580-6ab2-11e9-9c71-1822d501db9a.png)

This is with -c:
![image](https://user-images.githubusercontent.com/1630067/56913817-dca47880-6ab2-11e9-853a-7f8072198c57.png)

Looks like all ANSI codes are simply ignored while they work for other apps (I use ConEmu which supports ANSI codes by default)

Also this can be easily seen when I select e.g. nyan reporter:
![image](https://user-images.githubusercontent.com/1630067/56913900-11183480-6ab3-11e9-806a-d09a7bd965a9.png)

which finishes with such a butchery:
![image](https://user-images.githubusercontent.com/1630067/56913930-23926e00-6ab3-11e9-92f0-29125c942bae.png)

Just strange...

**Comment by inukshuk** [comment]
Which Electron version are you using?

Here is a screenshot using ConEmu:

<img width="605" alt="Capture" src="https://user-images.githubusercontent.com/325102/56914907-93a1f380-6ab5-11e9-9db6-15b0db5a24da.PNG">

**Comment by Mr1008** [comment]
Latest one: 5.0.0




On Mon, Apr 29, 2019 at 7:03 PM +0200, "Sylvester Keil" <notifications@github.com> wrote:












I think mocha will try to detect your terminal's capabilities, like color, and the auto-detection yields different results in Node.js and Electron (especially in renderer, which will likely get detected as a browser). Do colors works when you pass -c specifically?


As for missing stack traces, it depends on your exact configuration (most importantly if your tests run in main or --renderer). If you can point me to an example I can take a look.

**Comment by inukshuk** [comment]
OK I'm still on 4.x so that might be causing it. I'll upgrade our app later this week and check again.

On 4.x everything looks fine on Windows anyway.
