### ISSUE TITLE
Allow to pass extra switches to chrome

### ISSUE THREAD

**Issue by JCMais** [jprichardson/electron-mocha#141]
https://github.com/electron/electron/blob/master/docs/api/chrome-command-line-switches.md

I need that to be able to pass `--disable-namespace-sandbox`.

See this issue for the problem I'm trying to solve: https://github.com/electron/electron/issues/17972

**Comment by inukshuk** [comment]
You can pass extra switches using `--main` / `--require-main`. electron-mocha will load these files in the main process (regardless of the `--renderer` option)  before the `app.isReady()`.
