### ISSUE TITLE
How to load in electron application?

### ISSUE THREAD

**Issue by walterbelleville** [jprichardson/electron-mocha#142]
How do I use electron-mocha to test my electron application?   I can't get my electron application to load.   Do you have better examples on how to set up an electron application for testing.  I have looked at the test examples.  I am stuck on how to load in my application into electron-mocha to start testing different parts of the application.

**Comment by inukshuk** [comment]
electron-mocha is for unit testing in both Electron process types. you can use it for integration type tests where you load the whole application if you add your own scaffolding code, but by default it is intended for unit tests so you just require your source files and test them accordingly. (For an integration test framework, you might want to take a look at Spectron.)

You can look for similar apps to your own [which use electron-mocha](https://github.com/jprichardson/electron-mocha/network/dependents) for more examples.

**Comment by walterbelleville** [comment]
I couldn't get Spectron to work.
