### ISSUE TITLE
Using custom reporters in renderer mode has stopped working

### ISSUE THREAD

**Issue by twirlse** [jprichardson/electron-mocha#146]
Custom reporters has stopped working after upgrading electron-mocha from v6 to v8.

Steps to reproduce:
1. create a custom reporter from tutorial in a separate file (custom-reporter.js) from official tutorial at https://mochajs.org/api/tutorial-custom-reporter.html
2. use it as a reporter with --renderer option

Produced output: 
× ERROR: Unknown "reporter": custom-reporter.js

The same reporter works in main process and have been working before I have upgraded electron-mocha from v6 to v8.

I'm using: 
"electron-mocha": "^8.1.0",
"mocha": "^6.2.0",
"electron": "^5.0.7",
NodeJS: v12.6.0

**Comment by inukshuk** [comment]
Thanks!

Fixed in 8.1.1
