### ISSUE TITLE
app.getAppPath does not return my project app path

### ISSUE THREAD

**Issue by cxwithyxy** [jprichardson/electron-mocha#147]
electron-mocha:
```
app.getAppPath()
\\ M:\${your_project}\node_modules\electron-mocha\lib
```

electron:
```
app.getAppPath()
\\ M:\${your_project}
```

**Comment by inukshuk** [comment]
Yes, this looks right to me. You're running electron-mocha not your app, so this is the intended behavior. Why did you think this is a problem?

**Comment by cxwithyxy** [comment]
I use "process.cwd()" instead of "app.getAppPath()"

---

[my poject is here](https://github.com/cxwithyxy/Electron_path_helper)

I do some test by this command: **tsc && electron-mocha test/*.js**
