### ISSUE TITLE
electron-mocha fails silently when using renderer if specs are invalid javascript

### ISSUE THREAD

**Issue by KevinEady** [jprichardson/electron-mocha#148]
When using `electron-mocha` with a renderer process, if the spec files are invalid, the electron-mocha process returns success (a `0` exit code).

test.spec.js:

```javascript
some invalid js
```

command:
`electron-mocha --renderer test.spec.js`

Expected behavior: 
- Process exits with non-zero exit code

Actual behavior:
- Process exits with `0` exit code

```
➜  ~ cat test.spec.js                       
some invalid js
➜  ~ electron-mocha --renderer test.spec.js 

✖ ERROR: Unexpected identifier
➜  ~ echo $?                           
0
```

**Comment by inukshuk** [comment]
Can you give an example for the invalid spec?

**Comment by inukshuk** [comment]
This might be an Electron bug. We call `app.exit` with error code 1 [here](https://github.com/jprichardson/electron-mocha/blob/master/lib/run.js#L198).

**Comment by inukshuk** [comment]
`app.exit` closed the window, which in turn, kicked off another `app.exit` with a zero exit code. Will be fixed in the next release, thanks for reporting!
