### ISSUE TITLE
Support for --compilers js:babel/register

### ISSUE THREAD

**Issue by jg123** [jprichardson/electron-mocha#15]
How hard would it be to add support for the --compilers flag so tests could be written in ES6?

**Comment by vidbina** [comment]
PR #16 covers a very simple implementation that should make it possible. @jprichardson also mentioned another approach which involves using the `--require` flag as in `electron-mocha --require babel/register test/example.js` (I've seen this done for Mocha [here](https://gist.github.com/rauchg/93d8b831e286bcb30d84#2-writing-es6-tests), haven't looked into it for `electron-mocha` but I would guess it probably works just the same) or `electron-mocha --require ./babel.js test/example.js` where `babel.js` contains something like

```javascript
'use strict';

require('babel-core/register');
```

**Comment by jg123** [comment]
Excellent and perfect timing. You must have been reading my mind! I prefer the --compilers approach so as not to have the extra file. Thanks for the ESP!

**Comment by jprichardson** [comment]
Done in https://github.com/jprichardson/electron-mocha/tree/0.4.0

**Comment by jg123** [comment]
Thanks you two!
