### ISSUE TITLE
Run tests in browser with renderer also up

### ISSUE THREAD

**Issue by wleev** [jprichardson/electron-mocha#156]
It's already possible to test IPC calls from the `renderer` to `browser`, but is there any way to do the reverse? Spawn both `renderer` and `browser`, but perform the tests on the `browser` side?

**Comment by inukshuk** [comment]
Yes, that's possible, but there's currently no special API or infrastructure provided for this. You need to run the tests in `browser` so you start `electron-mocha` without the `--renderer` argument. In your test's setup code, you can open one or more browser windows and then have them run code that will trigger the IPC events your tests are expecting. Be sure to close all your windows again after the test runs!

You can [see an example here](https://github.com/tropy/tropy/blob/master/test/browser/wm_test.js) -- these are not unit tests, but sort of integration tests for a simple window manager which communicates via the IPC module. There are lots of abstractions there, but basically, these tests just open several windows and check if certain IPC calls come in.
