### ISSUE TITLE
How to test the renderer with Electron 10?

### ISSUE THREAD

**Issue by ffflorian** [jprichardson/electron-mocha#159]
Hi @jprichardson,

I have been using electron-mocha with great success so far with Electron <= 9. Now I am testing Electron 10 (beta), but electron-mocha fails to test the renderer. When running `electron-mocha --renderer "test.js" --no-sandbox` on a simple Electron 10 app (with a simple test in the `test.js` file), there is no output and electron-mocha is stuck. With Electron 9 the renderer tests work normally. Also, the main tests work as expected.

To quickly reconstruct the problem, I forked `electron-quick-start` and added electron-mocha. You can clone this repo and run the tests yourself:

https://github.com/ffflorian/electron-quick-start

// cc @inukshuk

**Comment by ffflorian** [comment]
Ah, the remote module was the problem. Thanks!

**Comment by inukshuk** [comment]
Thanks for reporting! Just pushed version 9.0.0 which [works with Electron 10](https://travis-ci.org/github/jprichardson/electron-mocha/jobs/705699577).

**Comment by inukshuk** [comment]
Just noticed that mocha changed some call signatures to be async -- so now there are likely race conditions when requiring modules in 9.x. I'll fix that later today!

**Comment by inukshuk** [comment]
Alright, 9.0.1 should play nice with the latest Mocha and Electron again.

**Comment by ffflorian** [comment]
Thank you :)
