### ISSUE TITLE
Support --expose-gc

### ISSUE THREAD

**Issue by szali** [jprichardson/electron-mocha#163]
Even when passing --expose-gc to electron-mocha, gc is not exposed. Tried putting the --expose-gc argument directly after electron-mocha or after everything else, did not work either way.

**Comment by inukshuk** [comment]
In electron, you would have to pass this option using the `--js-flags` switch. This might already work, actually, but if not we could certainly make it work in electron-mocha. However, I think this specific flag is not supported anymore? Are you using it in Electron elsewhere? Here's a [list of the currently supported flags](https://www.electronjs.org/docs/api/command-line-switches) -- for `--js-flags` you can click through to the Node.js docs.
