### ISSUE TITLE
Browser tests need `focusable: true`

### ISSUE THREAD

**Issue by artemave** [jprichardson/electron-mocha#171]
I have some renderer tests that emit (and assert on) events such as `blur`. Those only work when `document.hasFocus()` is true.

Electron-mocha starts electron window with `focusable: false` which results in `document.hasFocus()` `false`. `focusable` is set to `true` when the `--interactive` option is supplied, but that, ironically, doesn't change `document.hasFocus()`, because the focus is on devtools.

I can live with the latter - fair enough if you think about it - but I'd like to be able to set `focusable: true` for headless renderer tests.

Is it going to be a problem if `focusable` is set to `true` when `--renderer` is specified?

**Comment by inukshuk** [comment]
We can certainly consider adding an option for this, but are you sure this works reliably in a headless window?

Having tests rely on the DOM's focus state seems very brittle to me for unit tests and I'd try to mock that behavior instead (or, if this is more like an integration test, I'd create and destroy a window as part of the test instead of using the `--renderer` option).

In any case, this touches on the bigger issue that there are lots of window options which you may want to be able to control (especially security, context isolation etc.). Currently, if you have any special requirements there you can't really use `--renderer` but need to handle the whole window creation and teardown yourself. Making `--renderer` more powerful would be nice, but I wonder if it isn't outside of the scope of this package.

**Comment by artemave** [comment]
> We can certainly consider adding an option for this, but are you sure this works reliably in a headless window?

Those are old tests and they work on older versions of electron/electron-mocha. It's only after I upgraded dependencies today that the problem appeared. And so while investigating, I discovered that forcing `focusable: true` makes the problem go away.

**Comment by artemave** [comment]
> Having tests rely on the DOM's focus state seems very brittle to me for unit tests and I'd try to mock that behavior instead (or, if this is more like an integration test, I'd create and destroy a window as part of the test instead of using the --renderer option).

It's not actually about tests. `focusable: false` changes the browser behavior in a sense that `blur`, `focus` events can never ve received. In my case, I am lucky enough to have tests around that - that's because those are the tests for browser testing library! - but anything that is using that library with electron-mocha, and somehow relying on `blur`/`focus`, will have errors one layer removed from the problem, making it very hard to debug. And impossible to fix!

**Comment by artemave** [comment]
> In any case, this touches on the bigger issue that there are lots of window options which you may want to be able to control (especially security, context isolation etc.)

Adding an option to supply `window.conf.js` that would export a window config (a la `webpack.conf.js`) could be a good start?

**Comment by inukshuk** [comment]
The reason for setting this is that in some desktop environments creating a focusable window steals the focus away from the Terminal, which is extremely annoying. We definitely don't want to enable it by default.

https://github.com/jprichardson/electron-mocha/pull/83

**Comment by artemave** [comment]
> The reason for setting this is that in some desktop environments creating a focusable window steals the focus away from the Terminal, which is extremely annoying. We definitely don't want to enable it by default.
> 
> #83

While I appreciate the annoyance of focus grab, `document.hasFocus() == false` makes electron-mocha unrealistic browser environment - effectively rendering it unfit for any kind of browser testing. I would have thought that this should not be a default state.

**Comment by artemave** [comment]
Hey @inukshuk, perhaps my last comment was a bit aggressive. Apologies for that. But do you have more thoughts on this?

**Comment by inukshuk** [comment]
No worries!

I'm all in favor of adding the option to make the window started by the `--renderer` switch focusable, but as I mentioned I would prefer to solve this in a way that includes customizing other window options and web-preferences, ideally without adding separate CLI switches for each one. I have not considered it for too long, but your suggestion of using a separate config file for this is likely the best approach.
