### ISSUE TITLE
Test BrowserWindow WebPreferences Settings

### ISSUE THREAD

**Issue by petef19** [jprichardson/electron-mocha#182]
Hello,

looking for guidance on how to unit test the `webPreferences` settings (enableRemoteModule, contextIsolation, etc) that were used to create the main window, in either the `main` or `renderer` process.

In the emocha tests for the main process I get the error that `webPreferences` property is not defined on the main window of the Electron app.

In the renderer emocha tests, I get the same result when testing on the `window` object.

Any advice ?

Thanks !

**Comment by inukshuk** [comment]
I'm not sure what you're trying to do, but it sounds like you want to check what `webPreferences` were used to create a certain window, after the fact, right? I don't think there is an Electron API for that, but in general I would suggest to test for the effects. For instance, to test `enableRemoteModule` I'd use a renderer test that tries to use the remote module, expecting it to fail or succeed depending on your situation.

Or, perhaps, you're asking about how to change the `webPreferences` used to create the test window in `--renderer` tests? In that case, you can use `--window-config` with a JSON file containing your configuration.

**Comment by petef19** [comment]
the former, trying to confirm the `webPreferences` that a window was created with. There seems to be an API for a given window under the `webContents` property, such as `getWebPreferences` or `getLastWebPreferences`, but both throw `property does not exist` once I try to access them.

For now, I resorted to indirectly confirming the settings by spying on the `BrowserWindow` constructor and getting the passed in arguments...

**Comment by inukshuk** [comment]
You're right, you can get that object via `webContents` in the main process (not in renderer though!).

However, I doubt that this is reliable if you really want to test the effects of the preferences. I haven't confirmed this, but I would expect the options to reflect only the values that were used to create the web contents, not necessarily whether or not they are in effect. For example, on macOS there's a `vibrancy` option: even if you set it to true, the effect will only be applied if the current system preferences allow it -- I would guess that in such a case the web preference option would indicate the setting is on even when it is not actually in effect for the window. So if you want to test, e.g. that a given code creates a window with the remote module disabled, I'd test this by making sure renderer code really can't access remote.

**Comment by petef19** [comment]
> I'd test this by making sure renderer code really can't access remote

Could you provide a simple example ?

I'm not sure how to access `remote` in e-mocha renderer process.

Thanks !

**Comment by petef19** [comment]
Coming back to this as I played around with this more.

I'm really not sure e-mocha running as renderer works. I assume it  runs my Electron app and the window object would then allow me to run tests on the main window... ?

Because this does not work for me. My app has has these webPreferences:

```
webPreferences: {
    preload: this._path.join(__dirname, 'preload.js'),
    enableRemoteModule: false,
    nodeIntegration: false,
    contextIsolation: true,
    sandbox: true,
}
```

and in my Electron app in the renderer I access the electron module via `window.electron`. 

But in e-mocha, the `electron` object is `undefined` on the `window` object... what am I missing ?

Thanks.

**Comment by inukshuk** [comment]
> I'm really not sure how e-mocha running as renderer works. I assume it runs my Electron app and the window object would then allow me to run tests on the main window... ?

What is this assumption based on? How exactly would electron-mocha know about the webPreferences you use in your app? How would this work in apps that create different windows using different webPreferences?

Electron-Mocha runs Mocha in either Electron's main process or in a renderer process. It runs your _unit tests_, it does not know anything about your Electron app at all (if you're interested in _integration tests_, consider using something like [Spectron](https://www.electronjs.org/spectron)).

In electron-mocha, if you run your unit tests in the renderer process, it uses [its own webPreferences](https://github.com/jprichardson/electron-mocha/blob/master/lib/run.js#L185) by default. If your renderer code makes certain assumptions about the environment (e.g., context isolation, a context bridge that exposes 'electron' on the global window object and this sort of stuff) it's your job to create a suitable environment for the tests. Typically this is done using additional `--require` options and before hooks in mocha. You can also pass a custom `--window-config` as I've pointed out before (but electron-mocha will always run its own preload script).

> I want to test that remote and other objects are not available in my app's renderer, as per my webPreferences settings, would I use the window object for that ?

It's not clear which window object you're referring to, but the answer is no.

As I've pointed out before, if you want to test your window creation code, by definition, this is a test that must take place in the main process. To test only your own code you can stub `BrowserWindow` during the test to see the webPreferences your code passes in. If you want to test that the module really is not available in a window created by your code (that is, you're not only testing your usage of the Electron API, but the actual window), then you have to create the window during your test and then run additional code in that window to test your assumptions.

`window.electron.remote` does not exist by default, I'm assuming, your own preload code creates a context bridge to expose it, so in your own window, yes, you should test to make sure it's not available. You definitely also want to test that `require('electron').remote` does not work either.

But, again, you need to run these tests in a window that your own app created, if you want to test your window creation code. If you run it in electron-mocha's default window you're only testing electron-mocha's environment which is rather pointless.

**Comment by petef19** [comment]
Thanks for explaining that, it absolutely makes more sense now.

> you need to run these tests in a window that your own app created, if you want to test your window creation code.

ok, so how can I test for the existence of `.remote` in a window created in main ? 

It's unclear to me whether I need to run JS in the window via `win.webContents.executeJavaScript()` (although that does not return anything, so we're just looking for errors thrown... ?) or there are possibly window properties that I can directly test against... (?)

If the former (looking for errors thrown when executing JS), the risk with that is that these errors could be thrown because the JS code (written as a string) itself has errors...

Just trying to understand the best approach via e-mocha. A short example would speak a thousand words.

Thanks !!!
