### ISSUE TITLE
Get Document Title After Triggering Main Process Event 

### ISSUE THREAD

**Issue by petef19** [jprichardson/electron-mocha#183]
In my app, once an error has occurred, the app displays an error page which is loaded via the main process into the main window

While testing for this via e-mocha, I'm triggering an error, but I'm struggling to find a way to get the document title of the main window that just has been updated (with the error page).

Running e-mocha in main process, I can easily trigger the error, but there seems no way to access the document of the main window.

`my_window.getTitle()` returns `Electron` instead of the document title, while `my_window.webContents.getTitle()` returns an empty string.

I then tried to retrieve the document title from the document object by running e-mocha via --renderer flag, but the problem I'm facing there is that I cannot access certain Electron objects, in order to trigger an app error (for the error page to then display).

For example, on `import {app} from 'electron';` and then try to access properties of app, I get `app is undefined`...

Any suggestion on how to access the document title after triggering a main process method ?

Electron 12.0.2
E-Mocha 9.3.3
Win x64

Thanks !

**Comment by inukshuk** [comment]
When using `--renderer` you may need to pass your own `--window-config` (for example to enable the remote module).

The window title and document title are not necessarily the same. I think it used to be that the window title would be set to the document title on load, unless a title was specified when creating the window, though I'm not sure if that's still the case. `webContents.getTitle()` is supposed to return the document title, I think. If you get an empty string, I'd check if you really have a title set on the document using the renderer (and that the document has finished loading at the time of your test of course). In any case, I think this is a general Electron question not, specific to electron mocha. Happy to take a quick look if you post a more concrete example though.

**Comment by petef19** [comment]
Thank you, you were right. 

Had to wait for the window to load the new html string, and then `webContents.getTitle()` did return the correct value.

Thanks !
