### ISSUE TITLE
Can I run tests across multiple Electron instances?

### ISSUE THREAD

**Issue by jtlapp** [jprichardson/electron-mocha#192]
I need to test various configurations of initialization behavior for my module, each requiring a fresh instance of Electron. Is there a way to do this all in a single call to electron-mocha, or do I need to call it multiple times via script?

**Comment by inukshuk** [comment]
The electron-mocha binary starts Electron and electron-mocha itself runs fully in that Electron instance, so if I understand the question correctly, you'll need to start electron-mocha multiple times.

Of course your tests can launch Electron instances separately, but I suppose that's not what you're trying to do.

**Comment by jtlapp** [comment]
Got it. Thanks. That's what I've been doing.
