### ISSUE TITLE
Cannot get electron-mocha working in docker with Electron-17

### ISSUE THREAD

**Issue by gtritchie** [jprichardson/electron-mocha#195]
Using:

* electron-mocha 11.0.2
* electron 17.1.1

Tests run fine outside docker, via "npm test".

* running in a docker container (Ubuntu 20), with `xvfb` package installed
* launching tests via: `xvfb-run npm test`

package.json
```
"test": "electron-mocha --config ./test/unit/mocharc.json",
```

With that, I get:

> [10184:0317/223921.027286:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /src/src/node/desktop/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.

I've tried multiple approaches from here.

Chown/chmod the chrome-sandbox as suggested:

```
sudo chown root node_modules/electron/dist/chrome-sandbox
sudo chmod 4755 node_modules/electron/dist/chrome-sandbox
```

Now get:

> Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
> Trace/breakpoint trap (core dumped)

Then I tried to pass --no-sandbox using the technique of creating a .js file:

no-sandbox.js
```js
const { app } = require('electron');
app.commandLine.appendSwitch('no-sandbox');
```

Then invoking via:
```
"test": "electron-mocha --main no-sandbox.js --config ./test/unit/mocharc.json",
```

That didn't change anything.

What did work for me is to edit `electron-mocha` (in node_modules/.bin) and insert the line '--no-sandbox' here:

```js
function run (electron) {
  let args = [
    '--no-sandbox',
    join(__dirname, '../lib/main.js'),
    ...process.argv.slice(2)
  ]
```
Now the tests execute. Even if I put the chrome-sandbox back to its original owner/permissions.

Is there a correct way to pass --no-sandbox that I'm missing?

**Comment by inukshuk** [comment]
You should be able to pass command line options through the entry script: `electron-mocha --no-sandbox --config ./test/unit/mocharc.json`.

**Comment by gtritchie** [comment]
Yes! That did the trick. Don't know why I didn't try the easy thing first. Thank you!
