### ISSUE TITLE
Latest electron-mocha does not work with latest electron

### ISSUE THREAD

**Issue by artemave** [jprichardson/electron-mocha#212]
It doesn't find tests.

By trial and error, this seems to be the latest working combo:

```
    "electron": "27.3.11",
    "electron-mocha": "11.0.2"
```

**Comment by inukshuk** [comment]
I think it's the mocha 10.5 update that is responsible. I pushed a patch release that pins version 10.4.0 and works for me with Electron 31.

**Comment by inukshuk** [comment]
FYI fixed the underling issue. Version 13.0.0 should work fine again with Mocha 10.5.1 and later.
