### ISSUE TITLE
test 3 fails on OS X 

### ISSUE THREAD

**Issue by ErikBean** [jprichardson/electron-mocha#23]
I get this test failure when running electron-mocha --renderer:

[0m  1) describe: test 3 it: test 3:
[0m[31m     AssertionError: undefined === { [Function: Mocha]
  utils: 
   { escape: [Function],
     forEach: [Function],
     isString: [Function],
     map: [Function][0m[90m
      at Context.<anonymous> (/Users/beane/Code/electron-mocha/test/test3.js:8:12)
      at processImmediate [as _immediateCallback] (timers.js:374:17)
[0m

Looks like mocha is not attaching itsel;f to the winoidw 
I'm on electron-mocha v0.6.1, node v4.0.0, OS X Yosemite. Any idea what's going on here?

**Comment by jprichardson** [comment]
Does this still happen on `0.7.0` for you?

**Comment by ErikBean** [comment]
Yes, it does. Tests 2 and 3 are supposed to fail without the --renderer flag, right? (test 3 still failing for me even with the flag):
    electron-mocha  master %= electron-mocha --renderer ./test
    
    
      describe: test 1
    
        ✓ it: test 1
    
      describe: test 2
    hello storage!!
    Object { name: 'jp' }
    
        ✓ it: test 2
    
      describe: test 3
    
        1) it: test 3
    
    
      2 passing (67ms)
      1 failing
    
      1) describe: test 3 it: test 3:
         AssertionError: undefined === { [Function: Mocha]
      utils:
       { escape: [Function],
         forEach: [Function],
         isString: [Function],
         map: [Function]
          at Context.<anonymous> (/Users/beane/Code/electron-mocha/test/test3.js:8:12)
          at processImmediate [as _immediateCallback] (timers.js:374:17)

**Comment by inukshuk** [comment]
I just failed to reproduce this on a Mac with OS X 10.11.4 -- I think this can be closed.
