### ISSUE TITLE
Renderer test hang indefinitely

### ISSUE THREAD

**Issue by klepthys** [jprichardson/electron-mocha#3]
I have a simple test case, nothing specific. Located in a *test/* folder. As of now there is no browser-specific code.

When invoking : 
    electron-mocha 

tests pass well. However : 
    electron-mocha --renderer

hangs with no output. Even putting a log line on top of my only test file does nothing.

Any idea on how I can start debugging this?

**Comment by jprichardson** [comment]
Which OS? Which electron version?

**Comment by klepthys** [comment]
Linux, electron ^0.29.2.

**Comment by jprichardson** [comment]
Does it work if you pass in the test file as command line parameter?

**Comment by klepthys** [comment]
same thing : work like a charm without the option. hang with --renderer.

**Comment by jprichardson** [comment]
Confirmed. I got just a bit of time... looking at it now.

**Comment by jprichardson** [comment]
Figured it out. New release coming...

**Comment by jprichardson** [comment]
Fixed https://github.com/jprichardson/electron-mocha/releases/tag/0.2.1 Published. Thanks for reporting.

**Comment by klepthys** [comment]
works like a charm, thanks

**Comment by inukshuk** [comment]
Can you tell me what was causing this? I'm having the same issue now with 0.6.3 and electron 0.35/0.36 on Linux. (Had been working fine previously)

**Comment by mnquintana** [comment]
Ran into this too – in my case, all my tests run correctly, but the process never exits.

OS X 10.11.2, Electron 0.35.4

I just tested this with Electron 0.33.4 and electron-mocha exits as expected when running renderer tests.

**Comment by inukshuk** [comment]
Seems like it was completely unrelated; just a mixup of the new ipc module names. Fixed by #32 above.
