### ISSUE TITLE
process.stdout

### ISSUE THREAD

**Issue by inukshuk** [jprichardson/electron-mocha#39]
In the renderer `process.stdout.write` [is currently forwarded](https://github.com/jprichardson/electron-mocha/blob/master/renderer/console.js#L19) to remote `console.log` which implicitly adds line breaks; this in turn breaks the output of reporters like the default dots reporter.

I would like to find a way to avoid this, but wanted to ask first why the forwarding is necessary in the first place. The comment says it is to avoid socket errors which crash the tests, however, if I simply remove the lines in question I get no such errors (writes to `process.stdout` work fine and are printed to the terminal). Do you know if this is platform dependent (I'm on Linux) or perhaps something that has been fixed in recent Electron versions?

PS: out of curiosity I looked at [mochatron](https://github.com/tscanlin/mochatron/blob/master/bin/preload.js#L32) and they don't seem to patch `process.stdout` either.

**Comment by inukshuk** [comment]
In case forwarding is necessary on platforms other than Linux, perhaps this might work:

    Object.defineProperty(process, 'stdout', { value: remote.process.stdout })

Works fine for me at least (but like I said, on Linux this does not seem to be necessary in the first place)

**Comment by jprichardson** [comment]
It's almost certainly a relic of an old Electron version. I'd accept a PR to remove it entirely or at minimum, maybe it's safer to start with forwarding to remote process?

**Comment by inukshuk** [comment]
I'll test it on Win and OS X later and send a PR -- just wanted to make sure there was not a particular reason that made forwarding to console a necessity. Thanks!
