### ISSUE TITLE
allow local installs of electron-prebuilt

### ISSUE THREAD

**Issue by sdumetz** [jprichardson/electron-mocha#4]
When electron is not installed globally, electron-mocha can run when called through npm, but fails with an obscure error when called in command line.

*(full error below)*

Problem is that electron is not in path (because of local install) so resolvedPath is undefined. 
when called through ```npm start```, env var are set by npm that take care of this.
the **which** module provide a "path" option that should help.

The quick fix I came up with is to add process.env._ to PATH ([see](https://github.com/klepthys/electron-mocha/commit/3e066b7f3c4ec3ad0708e004aa02ec33eec31405)).

However it doesn't prevent users to type : 

    ./node_modules/electron-mocha/bin/electron-mocha

and still get the error. This is clearly not a good pratice while calling ./node_modules/.bin/exec_file is considered harmless so the fix might be good enough.

Another approach would be to force the user to install electron-prebuilt globally OR make an npm script  but in this case the error message should be made helpfull.

Steps that should reproduce the problem, with electron and electron-mocha installed locally : 

**in package.json's script**

    electron-mocha ./test.js #OK
    ./node_modules/.bin/electron-mocha ./test.js #OK
**in command line**

    /node_modules/.bin/electron-mocha ./test.js #FAIL

Error : 
```
child_process.js:1136
  var err = this._handle.spawn(options);
                         ^
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (child_process.js:1136:26)
    at exports.spawn (child_process.js:995:9)
    at runElectron (/MYDIR/node_modules/electron-mocha/bin/electron-mocha:16:18)
    at /MYDIR/node_modules/electron-mocha/bin/electron-mocha:8:29
    at F (/MYDIR/node_modules/electron-mocha/node_modules/which/which.js:72:25)
    at E (/MYDIR/node_modules/electron-mocha/node_modules/which/which.js:75:29)
    at/MYDIR/node_modules/electron-mocha/node_modules/which/which.js:83:16
    at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by FWeinb** [comment]
You can use something like this: `` ELECTRON_PATH=`node -p \"require('electron-prebuilt')\"`; electron-mocha [arguments] `` to use a electron local to your module.

**Comment by klepthys** [comment]
I know, I can also add node_modules/.bin to my path. there are even (more or less) automated ways to do that. However, I feek it should be a default behaviour for electron-mocha to detect it. 

The thing is it should be fixed once and for all. Not a partial solution like the one linked previously.

Maybe a simple : 

    {path.resolve(__dirname,"../node_modules/.bin")+":"+path:process.env.PATH}

This way the local install is always preferred (tha

**Comment by jprichardson** [comment]
I'd accept a PR to also resolve from `./node_modules/.bin`.

**Comment by klepthys** [comment]
I'll take some time next week to see if I can propose something clean

**Comment by ppitonak** [comment]
Is there any progress on this issue?
