### ISSUE TITLE
Add feature to test AMD modules using mocha

### ISSUE THREAD

**Issue by TheLevenCreations** [jprichardson/electron-mocha#43]
Hi @jprichardson 

This is really a great tool and helped me a lot for my project. Thanks very much for creating such tool.

Currently, I used commonjs to test. However, still, some modules are written in AMD format. Today, when I tried to test them, I met some problems. I believe others will meet the same problem to start testing using mocha under electron. It would be great if AMD testing can be added. 

Just a mark here, what I've done is like this:

1. Mocha needs --delay feature
2. use a loader to load the test js files
3. Then the loading is done, fire mocha.run() method

While I am struggling to make it work, I just found mocha browser support in page:
https://mochajs.org/#running-mocha-in-the-browser

It points out that an html can display mocha output:
```html
<html>
<head>
  <meta charset="utf-8">
  <title>Mocha Tests</title>
  <link href="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.css" rel="stylesheet" />
</head>
<body>
  <div id="mocha"></div>

  <script src="https://cdn.rawgit.com/jquery/jquery/2.1.4/dist/jquery.min.js"></script>
  <script src="https://cdn.rawgit.com/Automattic/expect.js/0.3.1/index.js"></script>
  <script src="https://cdn.rawgit.com/mochajs/mocha/2.2.5/mocha.js"></script>

  <script>mocha.setup('bdd')</script>
  <script src="test.array.js"></script>
  <script src="test.object.js"></script>
  <script src="test.xhr.js"></script>
  <script>
    mocha.checkLeaks();
    mocha.globals(['jQuery']);
    mocha.run();
  </script>
</body>
</html>
```

So my another thought it, would it be better that electron-mocha can display mocha results in electron renderer page instead of closing and displaying output in console?

Thank you very much

**Comment by inukshuk** [comment]
We've added a `--preload` option recently; this option only affects renderer tests -- your preload scripts are added as script tags to the head and the test suit runs on dom ready.

Closing this for now; please re-open in case this doesn't address all of your concerns.
