### ISSUE TITLE
npm install fails with npm@3.3.6 and node@5.0.0

### ISSUE THREAD

**Issue by ErikBean** [jprichardson/electron-mocha#46]
Trying to run `npm i -D electron-mocha ` with npm@3.3.6 and node@5.0.0 and gettting this error: 

> npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save-dev" "electron-mocha"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! Cannot read property 'localeCompare' of undefined

Looks like mocha depends on glob depends on graceful-fs.

> ├─┬ electron-mocha@0.8.0
│ ├─┬ electron-window@0.6.2
│ │ ├── is-electron-renderer@2.0.0
│ │ └── object-assign@3.0.0
│ ├─┬ fs-extra@0.22.1
│ │ └── jsonfile@2.2.3
│ ├─┬ mocha@2.2.5
│ │ ├── commander@2.3.0
│ │ ├─┬ debug@2.0.0
│ │ │ └── ms@0.6.2
│ │ ├── diff@1.4.0
│ │ ├── escape-string-regexp@1.0.2
│ │ ├─┬ glob@3.2.3
│ │ │ ├── graceful-fs@2.0.3
│ │ │ └─┬ minimatch@0.2.14
│ │ │   ├── lru-cache@2.7.3
│ │ │   └── sigmund@1.0.1
│ │ ├── growl@1.8.1
│ │ ├─┬ jade@0.26.3
│ │ │ ├── commander@0.6.1
│ │ │ └── mkdirp@0.3.0
│ │ ├─┬ mkdirp@0.5.0
│ │ │ └── minimist@0.0.8
│ │ └── supports-color@1.2.1
│ └─┬ which@1.2.4
│   ├─┬ is-absolute@0.1.7
│   │ └── is-relative@0.1.3
│   └── isexe@1.1.2

Looking at the package.json for the latest version of mocha, they have a hard dep on glob@3.2.3. So I guess there's nothing you can do about this, because the problem is in a dependency. Just something to be aware of is anyone else is having issues with node5/npm3

[npm-debug.log.zip](https://github.com/jprichardson/electron-mocha/files/167902/npm-debug.log.zip)

**Comment by ErikBean** [comment]
Update: I tried again with node@5.8.0 and npm@3.7.3 and everything works fine ([n FTW!](https://github.com/tj/n)). Looks like this issue must have been patched in npm and node.

**Comment by jprichardson** [comment]
> Update: I tried again with node@5.8.0 and npm@3.7.3 and everything works fine (n FTW!). Looks like this issue must have been patched in npm and node.

Cool. Thanks for checking this out!
