### ISSUE TITLE
No console output on Windows

### ISSUE THREAD

**Issue by andruhon** [jprichardson/electron-mocha#47]
Tests running as expected, but without any console output other than final exit status

Command in my package json:
```JSON
"test": "electron-mocha ./test/",
```

However the command below outputs mocha results as expected:
```JSON
"test": "electron node_modules/mocha/bin/_mocha ./test/ --enable-logging",
```

**Comment by andruhon** [comment]
Oh. It was actually **intellij console gobbling the output** (spawning output in a new window which was gone in half a second). Running the `npm test` in a separate cmd window works as expected.

I think that this issue with intellij worth documenting or fixing.

as expected apart from some wierd cyrillic letters instead of the "tick" in the output
```
  Desc 1
    тИЪ test 1
    тИЪ test 2

  2 passing (15ms)
```

**Comment by andruhon** [comment]
These changes in `electron-mocha/bin/electron-mocha` do make it work in intellij console, but I'm not sure that it is a correct way for this package:
```JavaScript
function runElectron (resolvedPath) {
  var args = process.argv.slice(2)
  args.unshift(path.resolve(path.join(__dirname, '../index.js')))

  //my stuff
  var electron = cp.spawn(resolvedPath, args);
  electron.stdout.on('data', (data) => {
    var str = data.toString('utf8')
    process.stdout.write(data)
  });
  //my stuff end

  ////original stuff
  //var electron = spawn(resolvedPath, args, { stdio: [process.stdin, process.stdout, 'pipe'] })
  //electron.stderr.on('data', function (data) {
  //  var str = data.toString('utf8')
  //  // it's Chromium, STFU
  //  if (str.match(/^\[\d+\:\d+/)) return
  //  process.stderr.write(data)
  //})
  //electron.on('exit', function (code) { process.exit(code) })
  ////original stuff end
}
```

**Comment by jprichardson** [comment]
How does regular Mocha handle this?

**Comment by andruhon** [comment]
Original mocha works well in intellij console.

**Comment by andruhon** [comment]
Also noticed that it swallows output from tee
if I do `npm test | tee out.txt` out.txt is empty

**Comment by andruhon** [comment]
The weird thing that one with tee outputs nicely in intellij. I'm puzzled, because you do almost stdio: 'inherit' and it should just work.

**Comment by andruhon** [comment]
This one works for both:
```JavaScript
function runElectron (resolvedPath) {
  var args = process.argv.slice(2);
  args.unshift(path.resolve(path.join(__dirname, '../index.js')));

  var electron = spawn(resolvedPath, args);
  electron.stdout.pipe(process.stdout);

  electron.stderr.on('data', function (data) {
    var str = data.toString('utf8')
    // it's Chromium, STFU
    if (str.match(/^\[\d+\:\d+/)) return
    process.stderr.write(data)
  });

  electron.on('exit', function (code) { process.exit(code) })
}
```

Maybe it is V8 bug?
