### ISSUE TITLE
Electron 0.37.4 -- Renderer hangs

### ISSUE THREAD

**Issue by inukshuk** [jprichardson/electron-mocha#51]
Has anyone else experienced this? Renderer tests hang indefinitely for me in Electron 0.37.4 (they're fine 0.37.3) -- I guess it might be related to the preload script not firing or something like that, but I haven't dug into it yet because I wanted to confirm first that I'm not the only one seeing this.

**Comment by jprichardson** [comment]
I haven't tried 0.37.4 yet, so I'm not sure. I typically lag about two weeks behind releases :(

**Comment by inukshuk** [comment]
I haven't figured it out completely, but this is definitely caused by Babel; running without a compilers flag works in 0.37.4. Closing this for now.
