### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by piti118** [jprichardson/electron-mocha#57]
I'm trying to setup a test electron-mocha.

The command looks like

```
cross-env NODE_ENV=test electron-mocha --renderer  --compilers js:babel-core/register --recursive --require ./test/setup.js test/**/*.spec.js
```

My .babelrc looks like (straight from chentsulin/electron-react-boilerplate)
```
{
  "presets": ["es2015", "stage-0", "react"],
  "plugins": ["add-module-exports"],
  "env": {
    "development": {
      "presets": ["react-hmre"]
    },
    "test": {
      "plugins": [
        ["webpack-loaders", { "config": "webpack.config.node.js", "verbose": false }]
      ]
    }
  }
}
```

and my setup.js looks like (will need to edit later but right now it doesn't even run)
```
import 'babel-polyfill';
import { jsdom } from 'jsdom';

global.document = jsdom('<!doctype html><html><body></body></html>');
global.window = document.defaultView;
global.navigator = global.window.navigator;
window.localStorage = window.sessionStorage = {
  getItem(key) {
    return this[key];
  },
  setItem(key, value) {
    this[key] = value;
  },
  removeItem(key) {
    this[key] = undefined;
  },
};
```

when I run it I'm getting
```
Error encountered in test/setup.js: Uncaught SyntaxError: Unexpected token import
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at xxx/node_modules/electron-mocha/renderer/run.js:26:3
    at Array.forEach (native)
```

replacing `electron-mocha --renderer` to just a normal `mocha` will work just fine. What did I do wrong?

**Comment by inukshuk** [comment]
I suggest you start with a minimal example first; in your case something about the babel setup does not work and overwriting all the DOM globals is problematic, too, obviously.

Without digging deeper, I can only say that using babel via `--compiler` works for me with electron-mocha but my babel configuration is limited to features which are not supported by Electron already. Electron is basically Node 5 and Chromium 49 -- that means you get almost everything from ES2015 for free.

**Comment by piti118** [comment]
OK I found the offending part.

https://github.com/jprichardson/electron-mocha/blob/master/index.js#L41

The require part doesn't go through the compiler before trying to require.
Will try to submit PR.
