### ISSUE TITLE
npm test on windows

### ISSUE THREAD

**Issue by szwacz** [jprichardson/electron-mocha#61]
I'm trying to `npm test` this repository after cloning on windows and I get error:
```
'.' is not recognized as an internal or external command
```

The line in package.json...
```
"test": "standard && ./bin/electron-mocha test/main && ./bin/electron-mocha --renderer test/renderer",
```
...isn't windows friendly. Googling doesn't bring any obvious hack to make it work. Does anyone have any idea?

**Comment by inukshuk** [comment]
Hmm.. does  "... && node bin/electron-mocha test/main ..." work?

**Comment by szwacz** [comment]
Yep! it works. Thanks.
