### ISSUE TITLE
Can't resolve 'electron'

### ISSUE THREAD

**Issue by sam-jay** [jprichardson/electron-mocha#65]
Using this command to run tests:
```shell
electron-mocha --renderer --compilers js:babel-register test/**/*.spec.js
```

Fails with error:
```shell
Error encountered in node_modules/babel-core/lib/transformation/file/index.js: Uncaught Error: /path/to/some.js: Can't resolve 'electron'
```

This is the import that fails:
```js
import { remote } from 'electron';
```

Can someone help me figure out what I'm doing wrong? Thanks.

**Comment by amilajack** [comment]
What was the solution to this?

**Comment by jprichardson** [comment]
@amilajack I'm guessing using a newer version of Electron would solve the issue.

**Comment by amilajack** [comment]
I've solved it. I was using webpack and I had to create an alias to the `electron-prebuilt` package.

**Comment by Aerlinger** [comment]
@amilajack What exactly did you do to solve it? I'm having the exact same issue.

**Comment by amilajack** [comment]
This:

https://github.com/amilajack/popcorn-time-desktop/blob/468b352497351965c2536574fafbf43a7e8acd8d/.babelrc#L19-L20

https://github.com/amilajack/popcorn-time-desktop/blob/468b352497351965c2536574fafbf43a7e8acd8d/package.json#L76

**Comment by amilajack** [comment]
@Aerlinger let me know if that works

**Comment by inukshuk** [comment]
Electron is now available via NPM as `electron` so an alias is probably not required if you install that package instead.
