### ISSUE TITLE
Hangs on Electron 1.2.0

### ISSUE THREAD

**Issue by szwacz** [jprichardson/electron-mocha#66]
Cloned the latest version of this repo. Run:

```
$ npm install
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

> electron-prebuilt@1.2.0 postinstall /Users/kuba/dev/electron-mocha/node_modules/electron-prebuilt
> node install.js


> electron-mocha@2.2.0 prepublish /Users/kuba/dev/electron-mocha
> npm test


> electron-mocha@2.2.0 test /Users/kuba/dev/electron-mocha
> standard && node bin/electron-mocha test/main && node bin/electron-mocha --renderer test/renderer



  mocha.opts
    ✓ --require modules are loaded

  describe: test 1
    ✓ it: test 1


  2 passing (16ms)
```

At this moment the process freezed. I see electron icon in the dock, but nothing is happening.
Does anyone encounter the same behaviour?

**Comment by inukshuk** [comment]
This is already fixed on Electron git so will go away with 1.2.1. If you want to work around it, you need to remove the web-security flag when starting the renderer tests. But I'd suggest to just stay on 1.1.3 until 1.2.1 comes out in the next few days. (Leaving this open for the time being)

**Comment by jprichardson** [comment]
> Does anyone encounter the same behaviour?

Yep, Electron 1.2.0 is broken: https://github.com/electron/electron/issues/5712

**Comment by szwacz** [comment]
Yep, release of v1.2.1 fixed the issue.
