### ISSUE TITLE
debugging tests in electron-mocha wit Visual Studio Code

### ISSUE THREAD

**Issue by stijnvn** [jprichardson/electron-mocha#68]
How do you set up a debugger like with ```_mocha```?

I'm trying to set up a launch configuration for unit tests in Visual Studio Code. The following configuration works for ```_mocha```. Any idea how to adapt this for ```electron-mocha```?

```
{
      "name": "Renderer unit tests",
      "type": "node",
      "request": "launch",
      "program": "${workspaceRoot}/node_modules/.bin/electron-mocha",
      "args": [
        "--renderer",
        "--recursive",
        "--reporter", "dot",
        "--require", "source-map-support/register",
        "${workspaceRoot}/build/renderer"
      ],
      "cwd": "${workspaceRoot}",
      "sourceMaps": true,
      "preLaunchTask": "build"
    }
```

**Comment by inukshuk** [comment]
electron-mocha forks out to Electron (Main process) and Renderer tests are forked out to a separate process (Renderer process). For debugging the main process [see here](http://electron.atom.io/docs/tutorial/debugging-main-process/); for debugging the Renderer process you can use the Debugger included in DevTools.

Both these options are not easily available via electron-mocha. I think we should allow to pass through the `--debug` options to Electron and provide another flag to show the Renderer test window (if possible setting a breakpoint too) to enable debugger support.

Both these options don't help you with VS Code though; I'm not using it myself so I can't comment on how to integrate their debugger.

**Comment by inukshuk** [comment]
See #70
