### ISSUE TITLE
Source maps support?

### ISSUE THREAD

**Issue by szwacz** [jprichardson/electron-mocha#69]
Should sourcemaps work in `--renderer` process? Because I can't get them to work. Tested inline and in separate file.

**Comment by inukshuk** [comment]
I'm not sure what you're trying to do? Source maps are meant for inspecting / reading compiled code, but not for running it -- electron-mocha would just run the compiled code so I don't see how source maps come into play here? Having said that, they should work just like they do in Chromium.

**Comment by szwacz** [comment]
My problem:
Let's use this boilerplate: https://github.com/szwacz/electron-boilerplate
And change one assertion so it doesn't pass. E.g. in file https://github.com/szwacz/electron-boilerplate/blob/master/app/hello_world/hello_world.spec.js change line to: 
```js
expect(greet()).to.equal('Hello Worldddddd!');
```

After running `npm test` (arrow in terminal output points at problematic line):

```
1) hello world greets:

      AssertionError: expected 'Hello World!' to equal 'Hello Worlddddddd!'
      + expected - actual

      -Hello World!
      +Hello Worlddddddd!
      
-----> at Context.<anonymous> (/Users/jakubszwacz/electron-boilerplate/build/spec.js:43:35) <--------- shows line in bundled file
      at tryOnImmediate (timers.js:543:15)
      at processImmediate [as _immediateCallback] (timers.js:523:5)
```

This problem touches everyone who is bundling code via babel or rollup.

Hope now I've explained it better.

Tried also inlining sourcemaps in different project, also without luck.

**Comment by szwacz** [comment]
Ok, looks like this is general problem of mocha and bundlers, not specific to this project. Will do more digging on the subject.

**Comment by szwacz** [comment]
Ok, I don't know what I did differently this time, but it works if the sourcemaps are inlined.

**Comment by myobie** [comment]
I believe one needs to have both `"sourceMaps": "inline"` and `"retainLines": "true"` in their `.babelrc`. Just in case anyone comes looking for this.
