### ISSUE TITLE
Workspaces on Mac OS X

### ISSUE THREAD

**Issue by Flaise** [jprichardson/electron-mocha#75]
On my mac, I like to keep my IDE in a workspace by itself so I can quickly switch to and from it with a four-finger swipe on the touchpad. When I start Electron with the electron-mocha package, despite no new window being displayed, it always pulls me back to the default workspace, which gets old when I'm using a file watcher to auto-run my tests each time I make a change. Is there a way to make Electron (specifically, the instance started by electron-mocha) not do this?

**Comment by inukshuk** [comment]
If we can, we should definitely make it possible to resolve this issue. I'm on Linux most of the time so I don't use OS X workspaces, but I can help debugging this.

When running the renderer tests we have to create a window (not shown by default, unless using the `--debug` option) so it seems just creating the window is enough to make OS X jump to that workspace. The only thing about this I found in the API is this [option](http://electron.atom.io/docs/all/#winsetvisibleonallworkspacesvisible) to make the window visible on all workspaces. Could you try if adding this option [here](https://github.com/jprichardson/electron-mocha/blob/master/index.js#L43) solves the issue?

**Comment by inukshuk** [comment]
This should be fixed by #83
