### ISSUE TITLE
Latest update broke support on Node.JS v4 and v5

### ISSUE THREAD

**Issue by MarshallOfSound** [jprichardson/electron-mocha#76]
Lot's of people still run tests on Node.JS 4.x and 5.x, especially considering 4.x is still LTS.

https://github.com/jprichardson/electron-mocha/commit/b6b6ad0caf02343fd68e0b0d6610a20071809f16#diff-f337a2a52c49917889f01434deb122dcR23

This line has dropped support for < v6 because they don't support default function parameters, can this be changed to a syntax that is supported on node.js v4.

Preferably also a `.travis.yml` file should be added to this repository to ensure support isn't lost in the future.

**Comment by inukshuk** [comment]
I removed the default parameter, sorry about that.

@jprichardson I can set up Travis if you like, but you'll have to enable to hook.

**Comment by jprichardson** [comment]
> @jprichardson I can set up Travis if you like, but you'll have to enable the hook.

Done!

**Comment by inukshuk** [comment]
Cool, tests should run on Node 4, 5, 6 on Travis now. Not that we have a lot of tests : ) (baby steps!)
