### ISSUE TITLE
Mocha requires Electron to be installed globally

### ISSUE THREAD

**Issue by patricia5859** [jprichardson/electron-mocha#81]
Hello,

I used mocha to test my Electron app and  got an error: "Can not find 'electron' in the $PATH and $ELECTRON_PATH is not set. Please either set $ELECTRON_PATH or 'npm install electron'". My workspace contains electron and not the machine itself. **Is there a way I could circumvent the installation of Electron on my build machine?** As, Electron will in turn require Node and NPM on the build machine.
Thanks!

**Comment by inukshuk** [comment]
Obviously, you need to install Electron on the machine where you want to run electron-mocha.

You can install Electron without first installing Node/NPM first: if you do that you need to make sure it is either on your $PATH or you have to set $ELECTRON_PATH to the Electron executable (if you install via NPM you don't have to do that).

**Comment by patricia5859** [comment]
Thanks for your response.

I do have Electron in my node_modules directory of the current project I am working on. I do not want to install Electron globally on my machine. Is there a work around?

**Comment by mweststrate** [comment]
If you start electron from an npm script it should be on the path
automatically. At least when using the `electron-prebuilt` package.

Op do 8 sep. 2016 om 19:40 schreef patricia5859 <notifications@github.com>:

**Comment by inukshuk** [comment]
Yes, you don't need to install Electron globally. You can either install it locally with npm (this is what you seem to have done), i.e., `npm i electron --save-dev` it should work fine (note that `electron` or `electron-prebuilt` should be listed in your package.json).

If, for some reason, you want to install a version of Electron locally but don't want it in your package.json you need to set $ELECTRON_PATH to the `electron` executable. For instance, if you installed it with `npm i electron` you can set `ELECTRON_PATH=<YOUR PROJECT ROOT>/node_modules/electron/dist/electron`.

**Comment by patricia5859** [comment]
Correct. 
electron-prebuilt is listed in my package.json. I am using electron-mocha for testing the electron app. Like I mentioned earlier when I run the test using "electron-mocha --renderer /myTestFilePath" command, it gives me an error: "Can not find 'electron' in the $PATH and $ELECTRON_PATH is not set. Please either set $ELECTRON_PATH or 'npm install electron'". And I do not want to install Electron globally. So am wondering how to run the tests.

**Comment by inukshuk** [comment]
Are you executing that on the command line directly or via an npm script? Like @mweststrate says, it should work when called via npm. If you're executing it directly then it looks as if you installed `electron-mocha` -- you need to make sure you actually run the locally installed version, i.e., run it via an npm script of like this: `$(npm bin)/electron-mocha --renderer test-file.js`.
