### ISSUE TITLE
Running tests steals focus from Terminal

### ISSUE THREAD

**Issue by MarshallOfSound** [jprichardson/electron-mocha#82]
When running tests inside `electron-mocha` on macOS with the terminal in "fullscreen" mode.  The test runner steals focus from Terminal when it launches the `BrowserWindow` which is very distracting / annoying when trying to view the test output inside Terminal.

This can be fixed with a combination of the `focusable` option when constructing your `BrowserWindow` and setting calling `app.dock.hide()` on macOS to not show Electron in the dock.

**Comment by MarshallOfSound** [comment]
This might be a duplicate of #75 but regardless #83 should fix it 👍

**Comment by inukshuk** [comment]
Makes sense -- good chance this fixes #75. Thanks!
