### ISSUE TITLE
Debugging no longer has access to to full dev tools

### ISSUE THREAD

**Issue by trodi** [jprichardson/electron-mocha#86]
Debugging is great in electron-mocha with `--debug-brk` flag. With the #82 fix though, you lose some of this functionality. You can still set break points and step through the code, but since the window isn't focusable, you lack the ability to interact with the running code via the console, which is very helpful at times.

Does it seem reasonable that, if you are running in debug mode, you'd want electron-mocha to steal focus? Would it be amenable if we set the window properties conditionally on the flag? If so, I can make a pull request with the change.

**Comment by inukshuk** [comment]
Yes, I think that's fine... I mean, if you want to use the debugger, you want to focus the window obviously.
