### ISSUE TITLE
Debugging main process

### ISSUE THREAD

**Issue by stijnvn** [jprichardson/electron-mocha#89]
Should the electron-mocha launch a debugger by default when debugging the main process?

Debugging the renderer process works fine, but when I try to debug the main process electron-mocha just seems to hang at the first breakpoint. How can I see/launch the debugger?

**Comment by inukshuk** [comment]
To debug the main process you need to use a separate debugger, like node-inspector, [compiled to work with your version of Electron](http://electron.atom.io/docs/tutorial/debugging-main-process/#use-node-inspector-for-debugging).
