### ISSUE TITLE
html files, like mocha-phantomjs?

### ISSUE THREAD

**Issue by stevenvachon** [jprichardson/electron-mocha#90]
PhantomJS' entry point is an HTML file, unlike Electron, so I can understand why there is either no support or no mention of support for using an HTML file as an entry point with this module. However, the nice thing about [mocha-phantomjs](https://npmjs.com/mocha-phantomjs) doing so is that we can also run those tests in real browsers.

**Comment by ngprasad** [comment]
@stevenvachon Do you know if there is a way we can run these tests in an Electron BrowserWindow? I am injecting some scripts into a BrowserWindow and need a way to test those.

**Comment by stevenvachon** [comment]
Sure, if you import mocha and run them, but they won't communicate back to the CLI. [mochatron](https://npmjs.com/mochatron) can do this, but it's [no longer supported](https://github.com/tscanlin/mochatron/issues/5#issuecomment-260563288).

**Comment by darkomenx** [comment]
Who and where is the base document launched by electron-mocha if we can't change this ?
What kind of file the CLI electron-mocha expects ? js ? html ?
