### ISSUE TITLE
Allow renderer process testing in electron-mocha

### ISSUE THREAD

**Issue by ngprasad** [jprichardson/electron-mocha#92]
I couldn't find an easy way to unit test renderer process using electron mocha. is this available on electron-mocha? If so can anyone point me how this can be done?

Thanks,
Nischal

@jprichardson @inukshuk

**Comment by szwacz** [comment]
Either I misunderstood your question, or you're looking for 'electron-mocha --renderer' :) It's well documented in the readme.

**Comment by ngprasad** [comment]
@szwacz I am actually using gulp-electron-mocha to run my tests. Is there a way I could run this by using gulp-electron-mocha?

**Comment by ngprasad** [comment]
My apologies for not reading the documentation. I added `renderer: true` as one of the options in gulp-electron-mocha and I am now able to test some of the functions that run in the renderer process. Thanks to @szwacz for pointing it out.
