### ISSUE TITLE
Assert not caught in async tests

### ISSUE THREAD

**Issue by cecilemuller** [jprichardson/electron-mocha#93]
The following async tests run fine directly in Mocha, whereas the error from the second test is not caught when running in electron-mocha instead:

````js
var assert = require('assert');

describe('Tests', function(){
	it('Test 1', function(done){
		setTimeout(function(){
			assert.ok(true);
			done();
		}, 100);
	});
	it('Test 2', function(done){
		setTimeout(function(){
			assert.ok(false);
			done();
		}, 100);
	});
});
````

**Comment by inukshuk** [comment]
Good catch, thanks.

@jprichardson although removing [our uncaught handler](https://github.com/jprichardson/electron-mocha/blob/master/index.js#L12) does not seem to fix it, I'm pretty sure that we cannot keep this as is (at least not the `app.exit`) -- do you think it's OK to remove the handler? (Mocha also listens for uncaught errors and matches them to the current test)

Like I said, removing it does not fix the issue so there has to be something more going on; may also have to do with recent changes in Mocha.

**Comment by jprichardson** [comment]
> do you think it's OK to remove the handler? (Mocha also listens for uncaught errors and matches them to the current test)

Yep, if Mocha does this, I think it's redundant if we do as well.

**Comment by inukshuk** [comment]
OK cool -- I'll try to fix this then (and will probably get rid of the handler in the process).
