### ISSUE TITLE
Running electron-mocha inside a Docker container

### ISSUE THREAD

**Issue by jviotti** [jprichardson/electron-mocha#95]
Have you ever tried running this inside a Docker container? I'm on an Ubuntu 14.04 base image, but get ELIFECYLE even after adding the `export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start` workaround.

```
> electron-mocha --recursive tests/cli -R min


npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test:main"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! etcher@1.0.0-beta.17 test:main: `electron-mocha --recursive tests/cli -R min`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the etcher@1.0.0-beta.17 test:main script 'electron-mocha --recursive tests/cli -R min'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the etcher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-mocha --recursive tests/cli -R min
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs etcher
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls etcher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /etcher/npm-debug.log
```

If you want to try this yourself:

```
git clone https://github.com/resin-io/etcher
cd etcher
```

Create a Dockerfile with the following contents:

```
FROM ubuntu:14.04

# Install dependencies
RUN apt-get update \
  && apt-get install -y \
  build-essential \
  jq \
  curl \
  python \
  git \
  software-properties-common \
  python-software-properties \
  libgtk2.0-0 \
  libxtst6 \
  libxss1 \
  libgconf-2-4 \
  libnss3 \
  libasound2 \
  xvfb

# NodeJS
RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - \
  && apt-get install -y nodejs
RUN npm config set spin=false
RUN npm install -g bower

# Ruby
RUN add-apt-repository ppa:brightbox/ruby-ng
RUN apt-get update
RUN apt-get install -y ruby2.3
RUN gem install scss_lint

ADD . /etcher
WORKDIR /etcher

ENV DISPLAY :99.0
COPY xvfb /etc/init.d/xvfb
RUN chmod +x /etc/init.d/xvfb
RUN /etc/init.d/xvfb start

RUN make electron-develop
RUN electron-mocha --recursive tests/cli -R min
```

Also create a file called `xvfb` in the same directory as the Dockerfile with the following contents:

```
#!/bin/bash

XVFB=/usr/bin/Xvfb
XVFBARGS="$DISPLAY -ac -screen 0 1024x768x16"
PIDFILE=${HOME}/xvfb_${DISPLAY:1}.pid
case "$1" in
  start)
    echo -n "Starting virtual X frame buffer: Xvfb"
    /sbin/start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    echo "."
    ;;
  stop)
    echo -n "Stopping virtual X frame buffer: Xvfb"
    /sbin/start-stop-daemon --stop --quiet --pidfile $PIDFILE
    echo "."
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
  echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
  exit 1
esac
exit 0
```

And finally, run:

```
docker build -f Dockerfile .
```

**Comment by scottrippey** [comment]
I've been successfully running this within a Docker container.  The easiest way, I've found, is to use `xvfb-run`, which automatically starts the Xvfb service and waits for it to be ready.

Here's approximately what I have:

```
FROM node:6
# Install xvfb:
RUN apt-get update &&\
    apt-get install -y libgtk2.0-0 libgconf-2-4 \
    libasound2 libxtst6 libxss1 libnss3 xvfb

...(copy and install app)...

RUN xvfb-run electron-mocha --recursive tests/cli
```

**Comment by jviotti** [comment]
Great, thanks a lot for the information. I'll give this a go soon and
will report back how it went.

On Tue, Jan 03, 2017 at 12:56:48PM -0800, Scott Rippey wrote:
> I've been successfully running this within a Docker container.  The easiest way, I've found, is to use `xvfb-run`, which automatically starts the Xvfb service and waits for it to be ready.
> 
> Here's approximately what I have:
> 
> ```
> FROM node:6
> # Install xvfb:
> RUN apt-get update &&\
>     apt-get install -y libgtk2.0-0 libgconf-2-4 \
>     libasound2 libxtst6 libxss1 libnss3 xvfb
> 
> ...(copy and install app)...
> 
> RUN xvfb-run electron-mocha --recursive tests/cli
> ```
> 
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jprichardson/electron-mocha/issues/95#issuecomment-270222421

-- 
Juan Cruz Viotti
Software Engineer

**Comment by jviotti** [comment]
It works great! Thank you very much for this! I'll close this issue but this would be worth mentioning somewhere on the README /cc @jprichardson
