### ISSUE TITLE
EPERM on exit, Windows only

### ISSUE THREAD

**Issue by CharlieHess** [jprichardson/electron-mocha#98]
Seems that it's not permitted to clean out its own cache directory. Especially bad because throwing the error instead of logging to `stdout` means that it blocks CI machines altogether.

![image](https://cloud.githubusercontent.com/assets/1865957/22946674/e618f600-f2ac-11e6-8be1-5416fdda29b7.png)

**Comment by inukshuk** [comment]
Are you perhaps opening windows in your tests which are not being closed? I remember having issues with cleaning out the temp folder on Windows when I forgot to close windows (in addition to the one managed by electron-mocha)

**Comment by CharlieHess** [comment]
I think this is actually on Electron; went ahead & filed https://github.com/electron/electron/issues/8685.
