### ISSUE TITLE
Test native extension

### ISSUE THREAD

**Issue by pronebird** [jprichardson/electron-mocha#99]
Hi, Is it possible to test native extension using electron-mocha? I tried but I can't match the version of native extension with electron. Electron-rebuild does not really help. Do you have any experience with this?

**Comment by inukshuk** [comment]
Electron-mocha simply runs mocha in an Electron main process or window, so you can test any native extension linked against the version of Electron you're testing. See [Electron's docs](http://electron.atom.io/docs/tutorial/using-native-node-modules/) for details; in most cases I would think electron-rebuild helps, but if you have special requirements you can always build the extension yourself.

**Comment by pronebird** [comment]
Hi,

Yes I use Electron-rebuild in one of projects but something doesn't work when I want to run it against my package. I raised similar issue on Electron-rebuild project. It seems to me that they rebuild packages that are listed under dependencies but not the package itself. Thought that maybe you had experience with this.

**Comment by inukshuk** [comment]
Well, have you installed the Electron headers for your target platform and rebuilt (e.g., with `node-gyp install` and `node-gyp rebuild`)?

(Closing this issue as it's not pertinent to electron-mocha itself).

**Comment by benlancaster** [comment]
I'm having the same problem. I can get my native extension built for electron and it works fine, but as soon as I try and test that native extension with electron mocha, I get the node version mismatch. @pronebird, did you make any headway with getting yours working?

**Comment by inukshuk** [comment]
Are you sure you're running electron-mocha with the same version of electron, for which you built the extension? `electron-mocha` uses the version specified by `$ELECTRON_PATH`, the local `electron` or `electron-prebuilt` module or the version of electron in your `$PATH` (in that order).

**Comment by pronebird** [comment]
@benlancaster I had related issue with electron-rebuild too. (https://github.com/electron/electron-rebuild/issues/150) So I think that was the culprit. I ended up running mocha with node-objective-c bridge to simulate Cocoa environment, however I since the issue I mentioned is already resolved I should migrate to electron-mocha once again. I have a feeling that it should work.
